### ISSUE TITLE
what

### ISSUE THREAD

**Issue by Klanker** [MythsList/RITZ-fixed#2]
what are the differences of this n normal ritz

**Comment by MythsList** [comment]
The original source code is broken, I fixed, made working menus and polished random stuff.

**Comment by Klanker** [comment]
> The original source code is broken, I fixed, made working menus and polished random stuff.

i assume by broken you mean these errors
`source/states/PlayState.hx:588: characters 11-26 : props.Player has no field ignoreDrawDebug
source/states/PlayState.hx:589: characters 16-31 : props.Tail has no field ignoreDrawDebug
source/states/PlayState.hx:595: characters 30-45 : flixel.FlxSprite has no field ignoreDrawDebug
source/states/PlayState.hx:573: characters 47-62 : props.Tail has no field ignoreDrawDebug`
would be pretty cool if you added like a txt file or smth with all the changes you made
